### ISSUE TITLE
moodle not displaying filter in tooltips

### ISSUE THREAD

**Issue by gengoac** [iarenaza/moodle-filter_multilang2#23] opened 2021-04-20 13:55 UTC
Not sure how this can be fixed, but moodle does not seem to be reading multilang filter tags in tooltips.

As per the below screenshot, I am hovering over a glossary but the tooltip is showing the full string with tags:

{mlang en}Time glossary{mlang}{mlang ja}用語集・時間{mlang}: Clock

Instead of showing Time Glossary or 用語集・時間 depending on whether the user has selected English or Japanese as their language.

Any way to fix this?

![image](https://user-images.githubusercontent.com/78563574/115407627-30d42600-a1be-11eb-8507-2a8e4f320818.png)

**Comment by iarenaza** [comment] 2021-04-20 16:16
I'm afraid that is a bug in the glossary module code, that may or may not be fixed in latest Moodle version. To be honst, I haven't checked the latest Moodle version for this particular issue. But there were similar issues reported here some time ago and I suggested opening bugs in the Moodle tracker to fix the problem.

The root of the problem is that if the glossary module doesn't call `format_string` or `format_text` with the text to display in the tooltip, the filtering plugins are not called. And thus the multilang2 filter can't do its part of the filtering.

So there is nothing the multilang2 filter can do in this case.

**Comment by gengoac** [comment] 2021-04-20 16:23
Got it, I'll open - or re-open - a bug in the Moodle tracker.

You did suggest similar for me regarding the rest of my site, and I have been working with the Edwiser team on their RemUI theme to find areas where ** format_string** or **format_text** are not being called, and they have been fixing them as we go. So, thank you for that :).

Hopefully the Moodle team will be able to fix this or advise something besides just leaving it as is.

Thank you for the quick reply.

**Closed** 2021-04-21 13:35 UTC
