### ISSUE TITLE
Not working with texts in H5P plugin activities

### ISSUE THREAD

**Issue by didier63** [iarenaza/moodle-filter_multilang2#16] opened 2020-01-24 13:38 UTC
Hi,
I tried with an H5P Documentation tool and the text remained as is with the tags {mlang}.
The table is prefix_hvp and the fields are name, json_content and filtered.
Kind regards,
Didier

**Comment by lucaboesch** [comment] 2020-01-24 15:18
Hi Didier. Can you check whether the other way to localize in Moodle (with the https://docs.moodle.org/38/en/Multi-language_content_filter <span lang="en" class="multilang">your_content_in English</span>) does display correctly?

**Comment by didier63** [comment] 2020-01-27 10:42
Hi Luca,
I can't do that because fields in H5P activities dont have the html edit mode.
And it seems that fields are stored in the DB in a JSON format.
Kind regards,
Didier

**Comment by iarenaza** [comment] 2020-01-27 11:58
Is the HP5 Documentation tool open source and available anywhere so I can test it?

Saludos.
Iñaki.

**Comment by didier63** [comment] 2020-01-27 14:29
Hi Iñaki,
Yes it is and it will be more an more integrated into Moodle. 
H5P website : https://h5p.org/
H5P integration in Moodle : https://h5p.org/moodle
The plugin page : https://moodle.org/plugins/mod_hvp
Kind regards,
Didier

**Comment by iarenaza** [comment] 2020-01-28 11:55
Hi Didier,

I already knew about H5P integration, but I wondered if you were using a specific external tool integrated via H5P, to check if the issue was with the multilang filter, the H5P integration plugin or the external tool.

P.S: EPFL alumni here :-)

Saludos.
Iñaki.

**Comment by izendegi** [comment] 2020-01-31 11:59
Hi Didier,

I've done some tests and the issue seems to be that **none of the Moodle filters are applied to the H5P content**, not this filter nor the standard ones (I've tested the [standard multilang filter](https://docs.moodle.org/en/Multi-language_content_filter) quoted by Luca and also others like [activity names auto-linking](https://docs.moodle.org/en/Activity_names_auto-linking_filter)). I've done this tests with the [H5P module plugin](https://moodle.org/plugins/mod_hvp) and also with the [other H5P integrations done on Moodle 3.8](https://docs.moodle.org/dev/Moodle_3.8_release_notes#H5P_integration).

So, been that the case, to address this issue correctly I suggest you to open a issue [on the Moodle tracker](tracker.moodle.org/) associated to the H5P component.

Ondo izan.

**Comment by iarenaza** [comment] 2020-03-04 17:53
Closing as "not a bug"

**Closed by iarenaza** 2020-03-04 17:53 UTC
