### ISSUE TITLE
Using multiple mlang in the same language

### ISSUE THREAD

**Issue by Laurynas-M** [iarenaza/moodle-filter_multilang2#28] opened 2022-03-16 10:06 UTC
Dear Colleagues,

I want to report an issue with the latest version of the mlang plugin in GitHub.
Here are the steps to replicate this issue:

Step 1: create Label activity and add the html code below:
                <div>
                                <h4><b>{mlang en}First text in English{mlang}{mlang de}First text in German{mlang}</b></h4>
                                <p><b>{mlang en}Second test in English{mlang}{mlang de}Second test in German{mlang}</b></p>
                </div>
Step 2: check the text and it will only display "First text in English" or "First text in German".
It will not display the second text of mlang: "Second test in English" or "Second test in German".
In addition, it will not display even other mlang texts with the same language.
Only the first mlang text will be displayed.

In the previous version, the second and other mlang texts in the same language were displayed.

Could you confirm this issue and resolve it?

Thank you in advance.

**Comment by lucaboesch** [comment] 2022-03-16 13:25
@Laurynas-M , when switching to the source code view, are there any tags around it, e.g.
```
<p>{mlang en}First text in English{mlang}{mlang de}First text in German{mlang}</p>

<p>{mlang en}Second test in English{mlang}{mlang de}Second test in German{mlang}</p>
```
or aren't there any?

**Comment by Laurynas-M** [comment] 2022-03-21 08:32
Hi @lucaboesch ,

Yes, we are using html tags <div>, <ul>,  <li>, <span> e.g.
<div><ul><li><span>{mlang en}First text in English{mlang}{mlang de}First text in German{mlang}</span></li></ul></div>
<div><ul><li><span>{mlang en}Second test in English{mlang}{mlang de}Second test in German{mlang}</span></li></ul></div>

It is working fine with the previous version of mlang plugin.

**Comment by lucaboesch** [comment] 2022-03-21 08:44
Okay, thanks a lot for specifying.
Would you mind mentioning the exact version it works/it does not work?
A assume with the latest you mean [https://github.com/iarenaza/moodle-filter_multilang2/commit/c667fbe5d70eb9f537610ddcd5af53ecc90ae142](https://github.com/iarenaza/moodle-filter_multilang2/commit/c667fbe5d70eb9f537610ddcd5af53ecc90ae142). Which is the one you observe it working fine the last time?

**Comment by lucaboesch** [comment] 2022-03-21 08:52
I can't reproduce the error BTW.
Could it be that it interferes with some other filter you have turned on? Would you mind naming all the filters in the exact precise order you have enabled (and whether for content, or for content and headers)?

**Comment by Laurynas-M** [comment] 2022-04-05 14:32
Hi @lucaboesch ,

I retested using newest version and this issue didn't occur. 
Maybe there was some other problems during installation.  
Please close this ticket.

Thank you.

**Comment by iarenaza** [comment] 2022-04-05 20:02
Closed as "not a bug"

**Comment by iarenaza** [comment] 2022-04-05 20:02
Close as "not a bug"

**Closed by iarenaza** 2022-04-05 20:02 UTC
Labels: not a bug
