### ISSUE TITLE
String "You are unenrolled from the course"... Not working with multilingual tags in course name

### ISSUE THREAD

**Issue by chiaravicere** [iarenaza/moodle-filter_multilang2#26] opened 2021-09-14 13:52 UTC
Hello, when a user unenrols from a course, there is a success alert who says you are succesfully enrolled from the course X. If X has {mlang} tags, they don't work.
With Boost theme: the ita and eng strings are attached together.
With custom theme: the fill text with {mlang} tags is printed.

![unenrol1](https://user-images.githubusercontent.com/25455823/133270232-68604044-c837-4746-a08c-cedc8b775678.png)
![unenrol2](https://user-images.githubusercontent.com/25455823/133270238-ffa0c1f5-9925-42ce-a1b2-86e024e53ef5.png)
![Immagine 2021-09-14 115417](https://user-images.githubusercontent.com/25455823/133270242-e9dfa0e2-a8b2-47ca-b3bc-984302da84dd.png)

**Comment by iarenaza** [comment] 2021-09-15 17:34
Hi @chiaravicere 

unfortunately this is a bug in Moodle core code. More specifically in the `enrol/self/unenrolself.php` file, in this particular line: https://github.com/moodle/moodle/blob/master/enrol/self/unenrolself.php#L53

If you look at that line, you will see that is uses the `$course->fullname` value as is. That value contains the whole `{mlang XX} ... {mlang}` tags and different language strings. The code should be calling `format_string` with that value, and passing that result as a parameter to the `get_string` function. Just like they do a few lines below, to present the dialog asking for unenrollment confirmation. This is the relevant line: https://github.com/moodle/moodle/blob/master/enrol/self/unenrolself.php#L61

So I guess you will need to create an issue in the Moodle tracker, asking the Moodle developers to fix it there. Once they fix that, the multilang2 plugin will do the right thing :smiley: 

I'm closing this issue a "Not a bug". Feel free to create a new issue if the Moodle developers fix the core code and the plugin still behaves wrong.

**Closed** 2021-09-15 17:35 UTC
Labels: not a bug

**Comment by lucaboesch** [comment] 2021-09-15 18:44
I created https://tracker.moodle.org/browse/MDL-72590 and wrote a fix.

**Comment by chiaravicere** [comment] 2021-09-16 09:39
Woah, thank you!

**Comment by lucaboesch** [comment] 2021-11-04 20:05
Moodle 3.10.8 and 3.11.4 due next monday nov 8, 2021 as well as 4.0, of course, will include the fix for this.
