### ISSUE TITLE
BigBlueButton Mod doesn't seem to recognize the filter in the activity.

### ISSUE THREAD

**Issue by tallthom** [iarenaza/moodle-filter_multilang2#17] opened 2020-04-07 05:17 UTC
In the BigBlueButton activity, {mlang} tags don't function in the description of the activity. If check the box so that I display the description on the course page, the tags work fine. There seems to be something awry when viewing the activity.

This shows the Japanese-only contents on the course page.
<img width="825" alt="Screen Shot 2020-04-07 at 14 15 21" src="https://user-images.githubusercontent.com/1357329/78632620-76d38a00-78da-11ea-9afe-2517874488be.png">

When I go into the activity, I see both descriptions.
<img width="1283" alt="Screen Shot 2020-04-07 at 14 16 01" src="https://user-images.githubusercontent.com/1357329/78632658-8f43a480-78da-11ea-872c-d0d2cf57ef8c.png">

**Comment by lucaboesch** [comment] 2020-04-07 06:23
Hi @tallthom and thanks for the report.
I enquired your issue.
It turns out that this works out on regular and other activities.
It seems to break in bigbluebuttonbn which is probably due to the programming there.
I encourage you to write to https://moodle.org/plugins/mod_bigbluebuttonbn or to open an issue under https://github.com/blindsidenetworks/moodle-mod_bigbluebuttonbn/issues and I am pinging @jfederico here.
It probably has to do with the function bigbluebuttonbn_html2text in bigbluebuttonbn/locallib.php which is too greedy.

Best,
Luca

**Comment by iarenaza** [comment] 2020-04-07 10:30
Using the Github search function in https://moodle.org/plugins/mod_bigbluebuttonbn repository, and looking for either `format_string` or `format_text` only gives two occurrences of `format_string` (for the page title and join URL link) and none for `format_text`. Those two functions are the ones that apply the enabled filters to the strings/texts before sending them to the browser. So it looks like they don't use them to output (and filter) the rest of the texts managed by the plugin.

**Comment by iarenaza** [comment] 2020-11-16 14:10
Closing as "not a bug"

**Closed by iarenaza** 2020-11-16 14:10 UTC
