### ISSUE TITLE
Problem with translations of themes items

### ISSUE THREAD

**Issue by ivanrueda** [iarenaza/moodle-filter_multilang2#8] opened 2017-01-27 17:13 UTC
Hi,
We are using the learning theme on moodle similar to https://moodle.org/plugins/theme_bcu , using multilang2, and the browser shows the text and ALL THE TAGS in any selected language. 

The problem is over the texts and descriptions on the front page marketing settings (like slider items, marketing blocks, brand, ...) and some personalized items. All the native buttons and course descriptions works great.

Hope you can solve the integration with the themes, I was reading in some forums that is an unsolved issue. https://moodle.org/mod/forum/discuss.php?d=326234 

Really thanks for this kind of efforts.

Regards Iván

**Comment by iarenaza** [comment] 2017-02-02 13:39
Hi Iván,

unfortunately there's nothing I can do on the filter plugin side. The filters are only run if the code that wants to display the text uses the format_string(), format_text() and related functions to display it.

This is the only way the filter has a chance to run and filter the language strings. So it's up to the theme developers to ensure that they use the above functions (or functions that ultimately call those functions internally) to display their texts / strings.

So I'm closing this as "not a bug", and I suggest that you open a bug with the theme authors to make them aware of the issue and the solution (you can reference this comment if needed).

Saludos.
Iñaki.

**Closed by iarenaza** 2017-02-02 13:39 UTC
