### ISSUE TITLE
Courses using this plugin filter do not work with the Moodle mobile app

### ISSUE THREAD

**Issue by tacru** [iarenaza/moodle-filter_multilang2#13] opened 2019-08-18 17:41 UTC
Hello, 

We have several courses with many languages using your plugin/filter. It works great on our site, while using the browser. However, we have tested it, and none of these pages appear properly when using the Moodle mobile app. I've done a few hours of research, without finding a solution. 

I've tried using Multi-Language Content (v2) format: `{mlang XX}content in language XX{mlang}`, as well as Multi-language format: `<span lang="XX" class="multilang">your_content_here</span>`, neither with success.

I've tried setting the language **_manually in the Moodle mobile app_**, as well as setting the **_default language in my device_**, and neither would display the proper content.

- Are we configuring something wrong? 

- Or, is this plugin but the app not supported? If so, Moodle advised us to contact you as the developer and provide to this documentation: [https://docs.moodle.org/dev/Moodle_Mobile_Remote_addons](https://docs.moodle.org/dev/Moodle_Mobile_Remote_addons) where it is explained how to add support to plugins in the Mobile app.

Thank you so much for your assistance!

**Comment by tacru** [comment] 2019-08-19 18:42
We have isolated the bug. The **Preferred language** (User > Preferences > Preferred language) controls the **_mlang tags_** in the app (the page content). However, the **language picker in the app** (… > App settings > General > Language) controls all the **_application terms for the course._** Is there any way for the language picker in the app to control the mlang tags?

**Comment by iarenaza** [comment] 2020-11-16 15:07
Hi @tacru

I'm sorry, but there is nothing the multilang filter plugin can do in this case. The filter is self-contained and only filters what it is told to do so. It doesn't drive the filtering process. It's the page rendering part of Moodle (or the Moodle app) which decides what parts to filter and what not. So if the the language picker in the app doesn't set the language for the filter or doesn't tell the filter to do its job, there is nothing I can do.

In the general case, if the official Multi-language format plugin (part of Moodle core) doesn't work, it's an bug with whatever other part of Moodle that produces or renders the content.

**Comment by iarenaza** [comment] 2020-11-16 15:08
Closing as "not a bug"

**Closed by iarenaza** 2020-11-16 15:08 UTC
