### ISSUE TITLE
Mlang V2 tags show up after upgrading to 3.10 version

### ISSUE THREAD

**Issue by nvillajos** [iarenaza/moodle-filter_multilang2#19] opened 2020-11-13 09:48 UTC
After upgrading to version 3.10 from 3.9.3, we noticed that the {mlng} tags show up in lists if used for more than one language, as in the following example:

Table of contents

{mlang en,fr}0:00 Introduction{mlang}
{mlang en,fr}0:39{mlang}Create declaration for outbound item at post
{mlang en,fr}1:22{mlang}Fill in the declaration header

From the back end, I have checked and the tags are properly placed. 

In the list item, I tried using {mlang en}0:00 Introduction{mlang} or {mlang fr}0:00 Introduction{mlang} and in those two separate instances, when only one language is involved, no {mlang} tags are shown. 

Would appreciate the help to resolve this.

**Comment by iarenaza** [comment] 2020-11-13 16:58
Sorry @nvillajos, but your example doesn't really help understand the issue. Could you post a screenshot showing what you have typed with {mlang} tags, and another one with the result you get when rendered by the plugin? That would help quite a bit :smiley:

**Comment by nvillajos** [comment] 2020-11-16 09:05
Hi @iarenaza, sorry. This is actually my first posting here and the 3rd time, unfortunately, to post this issue I encountered. I am a Moodle newbie and I posted it first in the Languages forum to check if someone else encountered the issue, and was told to post it in Tracker (it was closed as it was not a Moodle bag per se), and was directed that the right place to post should be here. 

I initially tried copy pasting all the marks/tags here, the way it was written from the back end, but when I previewed, it's not showing correctly. I attached the screens to provide more details. This is how it looks in our course page:

![tagsshowing](https://user-images.githubusercontent.com/74405345/99232645-772def00-27f2-11eb-88a6-7fdbfab012eb.PNG)

From the back end, this is how it's done:

![tagsbehind](https://user-images.githubusercontent.com/74405345/99232778-a47a9d00-27f2-11eb-9125-cf510e8af707.PNG)

As mentioned, the tags show up only if used for more than one language. I tried using it for a single language and there wasn't any problem at all. The text was shown with no mlang tags.
 
Please  let me know if you need more details.

**Comment by iarenaza** [comment] 2020-11-16 10:39
Hi @nvillajos 
I suspect you may be using an older version of the plugin that doesn't support the multiples languages syntax. That extended syntax was introduced in version 1.1.1 of the plugin (latest version is 1.1.2). Can you verify that before going down the rabbit hole? :smile:

**Comment by nvillajos** [comment] 2020-11-16 13:02
Hi @iarenaza, 

I'll have our System admin check the version we have as my access is limted. I 'll update you as soon as I have the info. Thanks.

**Comment by nvillajos** [comment] 2020-11-16 15:09
Hi @iarenaza,

Thanks very much for the help. After our System admin upgraded to the latest version (1.1.2), the text is now shown properly without any of the {mlang} tags. My apologies for the hassle raising this issue may have caused.

**Comment by iarenaza** [comment] 2020-11-16 15:20
Hi @nvillajos 

No need to apologize! I'm glad the issue was just that you were using an older version of the plugin.

Regards from an ex-Laussanoise :wink:

**Comment by iarenaza** [comment] 2020-11-16 15:20
Closing as "not a bug"

**Closed by iarenaza** 2020-11-16 15:20 UTC
