### ISSUE TITLE
Inconsistent behaviour with English child languages

### ISSUE THREAD

**Issue by michael-milette** [iarenaza/moodle-filter_multilang2#42] opened 2023-10-25 18:03 UTC
Hi @iarenaza ,

Thank you so much for your continued efforts with this plugin. I've been using it successfully with the English and Canadian French language packs for many years and highly recommend it to others. My sites and courses all contain thousands of instances of mlang tags in the following format:

{mlang en}English{mlang}{mlang fr}Français{mlang}

I really like that, regardless of whether I have the Canadian French child language pack or just the French language pack, this format with the 2 letter parent language has always worked for me. I say worked for me because I recently started using the Canadian English child language pack. The problem that I now observe is that, what works in French does not seem to work in English.

Using the same string mentioned above, when I view with the UI set to English, it works as expected. However, the text no longer appears at all if I am viewing using Canadian English. I expected the child English language pack to work the same way as the other child languages.

Anything you could do to fix this issue would be most appreciated. Let me know if you have any questions.

Best regards,

Michael

**Comment by iarenaza** [comment] 2023-10-29 18:24
Hi @michael-milette 

I'm afraid that this is caused by a "surprising behavior" from `get_language_dependencies()`. If you [have a look at it](https://github.com/moodle/moodle/blob/master/lib/classes/string_manager_standard.php#L88-L101), you will see that there is the following piece of text in its documentation string:

> English (en) is considered as the top implicit parent of all language packs and is not included in the returned list.

That is why `fr_ca` works as expected, as `get_language_dependencies()` returns an array containing both `fr_ca` and `fr`. But `en_ca` doesn't, as `get_language_dependencies()` returns an array containing just `en_ca` (but not `en`) See [1] below. Thus the `{mlang en} ...{mlang}` part is not used.

I ignore the reason why the above "surprising behavior" was decided. But according to my "git archeology" work, it's been like that for a long time (at least since MDL-22015, commit moodle/moodle@fb6b53724c, from 2010.04.04). And I couldn't find any stated reason for the decision, neither in the commit logs, nor in the tracker discussion.

Which leaves us with very little room for a fix, other than a ~~"hack"~~ heuristic that can fail in some cases. We could have a look at the value of `current_language()`, and if it begins with `en_`, assume that it is a language whose parent language is `en`. And add that extra `en` ourselves to the parent cache. But that heuristic breaks down the moment the child language is not named like that.

And probably breaks down too if the child language is actually two steps removed from English (i.e., `en` is the grandfather of the current language). And because I don't know why `en` was explicitly excluded from a language dependencies in the first place, I don't know what other unexpected side-effects we would be triggering. That is why I'm a bit hesitant to go that route.

On the other hand, you could use the feature added in version 1.1.1 as a workaround for this particular "pathological case". That is, use `{mlang en,en_ca}....{mlang}` instad of just `{mlang en_ca}...{mlang}`. I know it's not ideal, but at least it's a "known bad", as opposed to the potentially "unknown bad" of the heuristic I mentioned above.


[1]

```shell
$ cat > issue-42.php <<'EOF'
<?php
define('CLI_SCRIPT', true);

require(dirname(__FILE__).'/config.php');

$child_langs = array('fr_ca', 'en_ca');
foreach ($child_langs as $child_lang) {
    $parents = get_string_manager()->get_language_dependencies($child_lang);
    print('child language: ' .
          $child_lang .
          ' - parent languages: '.
          print_r($parents, true) .
          "\n");
}
EOF
$ php issue-42.php
child language: fr_ca - parent languages: Array
(
    [0] => fr
    [1] => fr_ca
)

child language: en_ca - parent languages: Array
(
    [0] => en_ca
)

$
```

**Comment by michael-milette** [comment] 2023-11-13 09:59
Thanks for the feedback.

The problem is, as a consultant, I've created dozens of Moodle sites over the years, now each with dozens or sometimes even hundreds of courses. I would say that about 2/3 of them are multi-language sites that make use of multilang v2. Most of them use the root English language however, it would be great if I could start migrating them to English (Canada). I've had requests from time to time, especially in the Government of Canada, for English with Canadian spelling and Canadian date formats.

It would be most appreciated if you could figure out how to make {mlang en} work with English (Canada).

Best regards,

Michael

**Comment by iarenaza** [comment] 2023-11-14 15:53
Hi @michael-milette 

after some head-scratching and some Moodle code spelunking, I think I may have found a possible solution that doesn't have too many "unintended side-effects". One known side-effect is that the solution I've found triggers issue #25 for multilang blocks where multilang English blocks are involved. Something that doesn't happend with the standard multilang2 filter, as 'en' is never considered as a parent language of a given multilang block.

If you are confortable with the above caveat, then you can try my possible solution by applying the follwing patch:

```patch
diff --git a/filter.php b/filter.php
index 044a5a2..0d99299 100644
--- a/filter.php
+++ b/filter.php
@@ -152,7 +152,14 @@ class filter_multilang2 extends moodle_text_filter {
         $this->replacementdone = false;
         $currlang = current_language();
         if (!array_key_exists($currlang, self::$parentcache)) {
-            $parentlangs = get_string_manager()->get_language_dependencies($currlang);
+            $strmgr = get_string_manager();
+            $parentlangs = $strmgr->get_language_dependencies($currlang);
+            if (count($parentlangs) > 0) {
+                $realrootisen = $strmgr->get_string('parentlanguage', 'langconfig', null, $parentlangs[0]);
+                if ($realrootisen === 'en') {
+                    $parentlangs = array_merge(array('en'), $parentlangs);
+                }
+            }
             self::$parentcache[$currlang] = $parentlangs;
         }
```

**Comment by iarenaza** [comment] 2023-12-11 15:30
Hi @michael-milette 

could you test the possible solution suggested earlier?

**Comment by michael-milette** [comment] 2024-10-07 04:18
Sorry, I know you are still waiting for me on this. It is still on my TODO list - I have not forgotten about this. I appreciate your patience.

Michael

**Comment by rezeau** [comment] 2024-10-23 14:50
Tested on Moodle 4.5 and moodle-filter_multilang2 version 2024101801.
I am not sure my problem is the same as the one reported earlier by @michael-milette ... What I can see in current moodle-filter_multilang2 is _an unwanted repetition_ of the "parent" language when the "child" language is selected in the UI.

Here's my code inside a Page content:
{mlang en}English{mlang} {mlang en_kids}English for kids{mlang} {mlang en_ca}Canadian English{mlang}
{mlang fr}français{mlang} {mlang fr_ca}français du Canada{mlang}

Results:
selected language:           | result displayed:
-------------------------------------------
English (en)                      | English
English (Canada) (en_ca)   | Canadian English
English (en_kids)               | English for kids 
Français (fr)                       | français
Français (fr_ca)                  | **français +** français du Canada

I just tested the patch suggested earlier by @iarenaza at https://github.com/iarenaza/moodle-filter_multilang2/issues/42#issuecomment-1810505761 and I'm sorry to report that not only it does not solve the problem at hand but it makes things _worse_ (at least for my problem)... With that patch even English sub-languages are displayed as well as English itself!
Results:
selected language:           result displayed:
--------------------------------------------------
English (en)                      | English
English (Canada) (en_ca)   | **English +** Canadian English
English (en_kids)               | **English +** English for kids 
Français (fr)                       | français
Français (fr_ca)                  | **français +** français du Canada

**Comment by rezeau** [comment] 2024-10-23 15:15
Oops! Just realized that my problem had already been reported in #25

**Comment by iarenaza** [comment] 2024-10-23 16:49
Hi @rezeau 

I can see that different people have different needs and expectations. But I'm confronted with a conflicting (and contradictory!) set of demands from you (and @Laurynas-M) and @michael-milette.

On the one hand, in this particular case, you want the language blocks to _**never**_ use the parent language to decide if a given block is displayed or not. Only the language specified in the `{mlang ...}` tag. On the other hand, @michael-milette wants the opposite: to _**always**_ use the parent language, even for languages that have `en` as their parent language.

And I'm pretty sure someone will show up demanding that some of the language blocks use the parent language while others don't :smile: And of course, they will want that the plugin guesses which behavior is expected in each case, without any hint or configuration from their side :grin:.

I can only think of one _potential_ solution, that will fit _**some**_ of the scenarios described above, but not every possible scenario. And it will mean that the admin and the content producers of the site will need to be involved, and proactively decide which way the plugin should work for their particular site and contents.

And because it's going to be a PITA for me to implement it, I'd like to put it out there for discussion before I even consider implementing it.

It revolves around adding a new configuration setting to the plugin. In that setting we would be able to select one of the following options (names will probably change):

1. Always use parent languages, excluding `en`
2. Always use parent languages, including `en`
3. Never user parent languages

Option 2 would fit what @michael-milette is asking for (if I understood it correctly). Option 3 would fit what you (@rezeau and @Laurynas-M) are asking for (again, if I understood it correctly).

Option 1, which would be the default value for the setting, would be to keep the same behaviour the plugin has had since the beginning.

Obviously this solution won't cover the case where some of the language blocks want to use the parent languges while others don't. For that, the setting would need to be set to '3. Never user parent languages', and then `{mlang ...}` blocks that want to use a given language and its parent(s), they would need to _**explicitly**_ list them in the `{mlang ...}` block. E.g., `{mlang en,en_CA,en_CA_kids} ....{mlang}`.

I don't see any other way to "round this square peg".

**Comment by rezeau** [comment] 2024-10-23 20:54
Hi @iarenaza 
Thanks for your detailed and considerate reply. I quite understand that it's quite hard to have a "one size fits all" solution to different users' different needs. The solution to offer 3 possible settings on a site might be the best, but as for me I certainly do not want to push you into further development work. As it is now your moodle-filter_multilang2 is a very useful tool and all Moodle users who need several languages for their contents must be grateful for your work.

**Comment by iarenaza** [comment] 2024-10-28 20:25
Hi @rezeau @michael-milette 

I just published to Github (but not to the Moodle plugins site yet) an alpha version of the plugin that includes the configuration setting (and associated behaviour) discusses before in this issue.The alpha version is available as a release here in Github, at https://github.com/iarenaza/moodle-filter_multilang2/releases/tag/2.0.5-alpha-1

If you could test that it works the way you expect, and you could also check the French language strings for the new settings (my French is very rusty these days) I would be very grateful!

Saludos,

Iñaki

**Comment by rezeau** [comment] 2024-10-28 22:04
@iarenaza I've just downloaded and tested your 2.0.5-alpha-1 branch on my localhost Moodle test site. It works as expected for me. The French strings for the new settings look OK as well. Good job (again)!

**Comment by michael-milette** [comment] 2024-10-28 22:47
I am away for 2 weeks. Will be happy to test when I get back.

**Comment by iarenaza** [comment] 2024-11-14 08:59
> I am away for 2 weeks. Will be happy to test when I get back.

Hi @michael-milette Did you have a chance to test the [alpha version available in Github as a release](https://github.com/iarenaza/moodle-filter_multilang2/releases/tag/2.0.5-alpha-1)?

**Comment by michael-milette** [comment] 2024-11-14 14:29
Hi @iarenaza 

Thank you for your patience. I installed the update and here is my feedback:

I found the information for the new setting quite confusing. I am not sure that people in general will know which option to pick.
<img width="800" alt="image" src="https://github.com/user-attachments/assets/be7ec36c-499e-41a5-9d74-94f64e0e80e0">

I actually had to read the history of this ticket to figure out which option to select. I used ChatGPT to help me rewrite the text for clarity which helped:
---

**Parent Language Behaviour**

The filter determines whether a language block should be displayed based on the languages specified in the block and the current language being used by the user. This matching process can follow three different approaches, known as "parent language behaviour":

1. Always use parent languages, excluding 'en' (Default).
* This is the default setting. The filter considers the languages listed in the language block's {mlang} tag, and all of their parent languages (up to but not including the root 'en' language).
* Example: If a language block specifies '{mlang en_us_k12}', it will only display if the user’s current language is 'en_us_k12' or 'en_us' but not 'en'.
* Note: English can still be used explicitly in the language block. For example, _{mlang en}This text will be shown when the user’s current language is 'en'.{mlang}_ will display the content when the user's language is 'en'.
2. Always use parent languages, including 'en'.
* This setting works like the previous one but includes the root 'en' as a valid parent language.
* Example: If a language block specifies '{mlang en_us_k12}', it will display if the user’s current language is either 'en_us_k12', 'en_us' or 'en'.
3. Never use parent languages.
* As the name suggests, no parent languages are used. The filter only matches the languages explicitly listed in the language block, without considering any parent languages.
* Example: If a language block specifies '{mlang en_us_k12}', it will only display if the user’s current language is 'en_us_k12', not 'en_us' or 'en'.

If you are unsure which one to choose, start with the default.

---
Once I selected the correct option, everything worked perfectly as expected. 

Thank you for your work on this. Your efforts are very much appreciated.

Best regards,

Michael Milette

**Comment by iarenaza** [comment] 2024-11-14 16:46
Thanks a lot @michael-milette 

I will update the description to use yours, with a couple of little changes for "language consistency". E.g., you use "the current language being used by the user" in one place, "the user's current language" in other(s), and "the user's language" in others. Are they the same thing? Are they slightly different things? I'd use the same term everywhere, to avoid creating that kind of doubt.

**Comment by michael-milette** [comment] 2024-11-14 18:05
Good catch! Like you, I would use consistent language even through they mean the same.

**Comment by iarenaza** [comment] 2024-11-27 00:23
I have committed the proposed language changes, and release a new version of the plugin (2.0.5). It's already available in the  Moodle plugins directory.

I'm closing this issue as fixed. Thanks a lot to @michael-milette and @rezeau for their invaluable help in coming up with a solution that can fit the apparently conflicting requirements :smile:.

**Closed by iarenaza** 2024-11-27 00:23 UTC

**Comment by michael-milette** [comment] 2024-11-27 04:02
Thank you @iarenaza !

**Comment by rezeau** [comment] 2024-11-27 07:58
Eskerrik asko @iarenaza !
