### ISSUE TITLE
Multilang filter for Activity title shows in calendar with {mlang} tag

### ISSUE THREAD

**Issue by hadgit** [iarenaza/moodle-filter_multilang2#12] opened 2018-12-20 06:46 UTC
I am using moodle 3.6 with multilang 2 plugin enabled, while adding activity like Quiz with multilang tag, the content displays correct in its respective pages for both language, but in calendar entry for students it shows with mlang tags and both the content together, this happens both on PC and Mobile App

**Comment by iarenaza** [comment] 2018-12-23 12:05
Hi @hadgit 

can you attach (or link to ) a couple of screenshots showing where you are defining the multi language calendar entry, and how it is displayed? Also, I you could specify the exact Moodle version you are using (see `version.php` at the root Moodle directory) and if you are using the standard calendar block or a 3rd party one, that would help a lot.

Thanks in advance.

**Comment by iarenaza** [comment] 2018-12-23 15:42
Hi @hadgit 

after having a look at the calendar code, I've discovered this is a bug (feature?) in the calendar events' management code. It simply doesn't consider using filters for event names and descriptions. So the multilang2 filter doesn't even have a chance to run and do its job.

With the patch below, it works as expected (in case you want to open an issue in the Moodle bug tracker).

So I'm closing this issue as "not a bug".

```diff
[moodle-36 ((v3.6.1) *%)] $ git diff
diff --git a/calendar/classes/local/event/factories/event_abstract_factory.php b/calendar/classes/local/event/factories/event_abstract_factory.php
index ff697dd5817..3bb8e2c12da 100644
--- a/calendar/classes/local/event/factories/event_abstract_factory.php
+++ b/calendar/classes/local/event/factories/event_abstract_factory.php
@@ -171,7 +171,7 @@ abstract class event_abstract_factory implements event_factory_interface {

         $event = new event(
             $dbrow->id,
-            $dbrow->name,
+            $dbrow->name = format_string($dbrow->name),
             new event_description($dbrow->description, $dbrow->format),
             $category,
             $course,
diff --git a/calendar/classes/local/event/value_objects/event_description.php b/calendar/classes/local/event/value_objects/event_description.php
index 3d4db691a3e..9d3e3addcfe 100644
--- a/calendar/classes/local/event/value_objects/event_description.php
+++ b/calendar/classes/local/event/value_objects/event_description.php
@@ -55,7 +55,7 @@ class event_description implements description_interface {
     }

     public function get_value() {
-        return $this->value;
+        return format_string($this->value);
     }

     public function get_format() {
```

**Closed by iarenaza** 2018-12-23 15:42 UTC

**Comment by hadgit** [comment] 2018-12-23 15:53
![image](https://user-images.githubusercontent.com/24873357/50385190-2da9f780-06e2-11e9-8eb3-53dc3490fb08.png) (with mlang tag)

![image](https://user-images.githubusercontent.com/24873357/50385195-516d3d80-06e2-11e9-82b3-83a4be8cdf86.png)
(without mlang tag)


I am using the following: 
1. Multi-Language Content (v2)filter_multilang2 | 1.0.12018070401
2. Academi theme_academi | v3.6.12018121000
3. Moodle Version with Default Calendar (no plugin)
defined('MOODLE_INTERNAL') || die();

$version  = 2018120301.00;              // 20181203      = branching date YYYYMMDD - do not modify!
                                        //         RR    = release increments - 00 in DEV branches.
                                        //           .XX = incremental changes.

$release  = '3.6.1 (Build: 20181205)'; // Human-friendly version name

$branch   = '36';                       // This version's branch.
$maturity = MATURITY_STABLE;             // This version's maturity level.
