### ISSUE TITLE
filter_multilang2 couses information of an activity to be transparent

### ISSUE THREAD

**Issue by franszwijnenberg** [iarenaza/moodle-filter_multilang2#44] opened 2023-12-08 11:14 UTC
When using the filter_multilang2 version 2022120900 with Moodle LMS 4.1.6 (build: 20231009) and format_tiles (version 2023030500) The Edit On gives a strange effect.

![image (1)](https://github.com/iarenaza/moodle-filter_multilang2/assets/75476440/1721a86e-380e-4d78-9345-548795307f41)

The information of a activity is transparent over the rest of the screen.

**Comment by izendegi** [comment] 2023-12-11 10:16
Hi @franszwijnenberg 

It seems like the multilang2 filter is applied in a way that breaks the HTML, not a bug of the filter itself. 

You should inspect the place where the filter is used and check that there is no HTML tags opened outside and closed inside the {mlang} tags (or viceversa).

**Comment by franszwijnenberg** [comment] 2023-12-19 10:53
is this what you mean by HTML tags starting inside en ending ouside the {mlang} tags:
  <p dir="ltr"><strong>El Equipo de Coordinación de Aprendizaje Mutuo</strong><strong style="font-size: 0.9375rem;">{mlang}</strong></p>

**Comment by iarenaza** [comment] 2023-12-21 16:34
Yeah, that code snipped looks fishy. The closing `{mlang}` tag is "inside" the `<strong> tag (and inside the `<p>` tag. When the filter is run, if the user current language is not the one beloging to that particular `mlang` tag (I can't say for sure which language that is, as the opening `mlang` tag is not shown in the snippet), the filter will remove everything between the opening tag and that closig tag. And will leave the `</strong></p>` trailing tags untouched (they are outside the "mlang block", so to speak).

**Comment by franszwijnenberg** [comment] 2023-12-22 07:40
So this is the complete HTML forum discription what goes wrong
![image](https://github.com/iarenaza/moodle-filter_multilang2/assets/75476440/2622d8e8-4051-41ab-9e7b-3a05240a27a2)

**Comment by iarenaza** [comment] 2023-12-28 17:11
@franszwijnenberg 

I am afraid you will need to provide detailed instructions on how to reproduce the issue you are having. I have never used that format plugin myself, and I have tried. But then I wasn´t able to reproduce the issue, because it is no clear to me how to do it from your description.

So please, post a step by step list of instructions so we can try to reproduce it.

Thanks in advance :smiley: 

Saludos.
 
Iñaki.

**Comment by franszwijnenberg** [comment] 2024-03-06 14:03
Hi Iñaki.
Sorry it took a while.
I have created a clip to show what is happening
[Course and category management _ Mutual Learning Program.zip](https://github.com/iarenaza/moodle-filter_multilang2/files/14510863/Course.and.category.management._.Mutual.Learning.Program.zip)

**Comment by franszwijnenberg** [comment] 2024-03-06 14:04
In a ZIP file because the original is to big

**Comment by iarenaza** [comment] 2024-04-06 14:11
Hi @franszwijnenberg 

I had to watch your video several times, until I realized what was going on. I had to watch the video at  at 0.25x speed to be able to see the problem. I had to see that slow to be able to see the underlying source HTML code of your blocks. Because watching it at normal speed, that source code it not visible (it's a mere blip) and we only see the resultant formatted HTML .

Here's a screenshot that I took from your video, showing the source code of one of the "problematic" pieces of content, that the multilang2 filter is supposed to be breaking. I added some visual elements, to help with the problem discussion:

![Screenshot_20240331_125907-annotated](https://github.com/iarenaza/moodle-filter_multilang2/assets/241751/3a071a64-2afb-489a-a3a8-3f1de103e864)

If you download the image and zoom it a bit, you will see that there are several numbers inside a circle in red. Those are the places where the `{mlang...}` tags are found in the HTML source code.

If you look at the one marked with the number (1), you will see that the opening `{mlang en}` tag is placed just after a `<p>` opening tag. The corresponding closing `{mlang}` tag is the one marked with the number (2). If you have a careful look at that tag, the next HTML tag is a *closing* </li> tag. The multilang2 filter will keep or remove all the HTML that is between the (1) and (2) mlang tags.

As you can clearly see from the image, the filter will leave the final HTML output "broken", because the mlang tags are not correctly placed! You are placing them "in the middle" of full HTML elements (a `<li>`, a `<ul>`, etc). So it's no wonder you see the "broken things" you showed in the images that you attached when you opened the issue.

It looks like the source HTML code is coming from another tool, that you pasted in the description input area (all those `<span data-translationhash=...>` suggest that). So, if you are placing your `{mlang ..}` tags in that text by hand, then I humbly suggest you that you switch to the "Source Code View" and place them carefully. Making sure you place them *between* existing content tags (that is, after a closing content HTML tag and before the opening of the next content HTML tag), and not "in the middle of one HTML tag content".

If those `{mlang ...}` tags are placed by the same tool that generates the source HTML code for the content, then you need to fix the tool, to make sure that, again, they are placed *between* content tags.

So I'm going to close this issue as "not a bug".

**Closed by iarenaza** 2024-04-06 14:11 UTC
Labels: waiting for input
