### ISSUE TITLE
Not working on "Available Courses" block in the home page.

### ISSUE THREAD

**Issue by sirpepo** [iarenaza/moodle-filter_multilang2#6] opened 2016-02-29 10:26 UTC
In the homepage as guest, the "Available Courses" block is printing the markup for languages and not only the content for the current language.

**Comment by iarenaza** [comment] 2016-03-03 10:07
Hi,

could you provide a screenshot showing the problem? I would need to identify what content the markup for languages is related to (title of the course, description, shortname, etc.) and how/where it is shown.

Thanks in advance.

**Comment by iarenaza** [comment] 2016-07-12 20:40
Closing this, as I've been unable to reproduce the problem (and no feedback has been received).

**Closed by iarenaza** 2016-07-12 20:40 UTC
