### ISSUE TITLE
Multi lang 2 use with the Buttons Format 

### ISSUE THREAD

**Issue by mcwe** [iarenaza/moodle-filter_multilang2#11] opened 2018-09-21 23:15 UTC
Hello 

We recently started developing in two languages English and French. We were trying to utilize the {mlang en}{mlang} and {mlang fr}{mlang} in the buttons format layout for the course to no avail. Has anyone successfully been able to use this?

Any help we be greatly appreciated.

Thanks!

Blessings,
Sophia

**Comment by iarenaza** [comment] 2018-09-24 08:35
Hi Sophia,

the filter works on any string that's ultimately processes by filter_string() or filter_test() core functions. This usually includes user generated content like forum posts, labels, descriptions, etc. And also some headings  (like course names) if you configure the filter to apply to "Content and headings" (instead of the default for just "Content).

But I highly suspect that the code for the Buttons format doesn't call format_string() or format_text() when building the labels for the buttons. In fact, I've had a look at the code for the Buttons format plugin, and it doesn't call format_string() or format_test() anywhere in the code. I've added it myself just to try it, and as soon as I added the call to format_string() in the right place and enabled the multilang2 filter for "Content and headings", it has started working as expected.

So this is definitely a  bug in Buttons format plugin (I see you've also opened a bug in it's Github repo).

Closing this as "not a bug".

**Closed by iarenaza** 2018-09-24 08:35 UTC
