### ISSUE TITLE
Second and other mlang texts are not displayed of the same language

### ISSUE THREAD

**Issue by Laurynas-M** [iarenaza/moodle-filter_multilang2#30] opened 2022-04-26 07:28 UTC
Dear colleagues,

I want to report an issue in moodle-filter_multilang2 plugin related to committed fix KepaUrzelai@0174b63.

The fix has solved the Canadian French (fr_ca) child's language issue reported in this ticket https://github.com/iarenaza/moodle-filter_multilang2/issues/25.

But a new issue occurs. Here are the steps to replicate this issue:
Step 1: create Label activity and add the html code below:

> `<div><ul><li><span>{mlang` en}First text in English{mlang}{mlang de}First text in `German{mlang}</span></li></ul></div>`

> `<div><ul><li><span>{mlang` en}Second test in English{mlang}{mlang de}Second test in `German{mlang}</span></li></ul></div>`

Step 2: check the text and it will only display "First text in English" or "First text in German".
It will not display the second text of mlang: "Second test in English" or "Second test in German".
In addition, it will not display even other mlang texts with the same language.
Only the first mlang text will be displayed.

Could you confirm this issue with committed fix KepaUrzelai@0174b63?

If confirmed, could you fix it?

Thank you in advance.

**Comment by iarenaza** [comment] 2023-08-18 08:31
Hi @Laurynas-M 

Yes, I can confirm this is an issue with "commited fix" [KepaUrzelai/moodle-filter_multilang2/commit/0174b63](https://github.com/KepaUrzelai/moodle-filter_multilang2/commit/0174b63), because that "fix" is not really a fix (as @KepaUrzelai himself said in #25).

It is also the reason why that "commited fix" is not actually commited in the official plugin repo (this one): because it doesn't really fix issue #25 (except for a single, very special, use case, but not for the general case).

That is why I'm closing this issue, and marking it as "not a bug" (because this "issue" doesn't happen if you don't apply @KepaUrzelai 's patch)

**Closed by iarenaza** 2023-08-18 08:31 UTC
Labels: not a bug
